CREATE DATABASE BANK_PROJECT_DB;
USE DATABASE BANK_PROJECT_DB;
USE SCHEMA PUBLIC;

 SELECT * FROM FACT_TRANSACTIONS ;

 SELECT COUNT(*) FROM FACT_TRANSACTIONS;


 SELECT sender_name, amount, type, is_high_value 
 FROM FACT_TRANSACTIONS 
 ORDER BY amount DESC 
 LIMIT 10;